---
title: Dataframe
subtitle: Mixed
date: Feb 11, 2023
author: Sungkyun Cho
---

## R의 데이터 구조와 변수 타입

주로 **벡터**와 **데이터프레임**을 다룸

![](images/dataframe.png){width=400}  
Source: R in Action by Rob Kabacoff

In [ ]:
library(tidyverse)

cps <- mosaicData::CPS85 # mosaicData package의 CPS85 데이터셋
cps

In [16]:
library(IRdisplay)
library(repr)

options(repr.html.deduplicate = TRUE)
cps

    wage  educ race sex hispanic south married exper union age sector
1    9.00 10   W    M   NH       NS    Married 27    Not   43  const
2    5.50 12   W    M   NH       NS    Married 20    Not   38  sales
3    3.80 12   W    F   NH       NS    Single   4    Not   22  sales
4   10.50 12   W    F   NH       NS    Married 29    Not   47  clerical
5   15.00 12   W    M   NH       NS    Married 40    Union 58  const
6    9.00 16   W    F   NH       NS    Married 27    Not   49  clerical
7    9.57 12   W    F   NH       NS    Married  5    Union 23  service
8   15.00 14   W    M   NH       NS    Single  22    Not   42  sales
9   11.00  8   W    M   NH       NS    Married 42    Not   56  manuf
10   5.00 12   W    F   NH       NS    Married 14    Not   32  sales
11  24.98 17   W    M   Hisp     NS    Married 18    Not   41  prof
12  20.40 17   W    M   NH       NS    Single   3    Not   26  prof
13  25.00 14   W    M   Hisp     NS    Single   4    Union 24  service
14  13.98 14   W    M   NH       NS    Single  14    Not   34  other
15   3.50 12   W    M   NH       NS    Married 35    Not   53  clerical
16   5.00 14   W    M   Hisp     NS    Single   0    Not   20  sales
17  10.00 16   W    M   Hisp     NS    Married  7    Union 29  manag
18  15.00 16   NW   M   NH       NS    Married 26    Union 48  manag
19   5.83 13   NW   M   NH       NS    Single   3    Not   22  service
20   9.10 13   W    M   Hisp     NS    Single  16    Not   35  clerical
21  11.25 17   NW   F   NH       NS    Married 32    Not   55  clerical
22  13.00 12   NW   M   NH       NS    Married 25    Union 43  service
23   8.00 14   W    F   NH       NS    Single  15    Union 35  clerical
24   4.28 12   W    F   NH       NS    Married 38    Not   56  service
25   7.88 16   NW   M   NH       NS    Married 17    Not   39  clerical
26   6.94 12   W    F   NH       NS    Single   7    Not   25  service
27  24.98 17   W    F   NH       NS    Single   5    Not   28  prof
28  10.00 14   W    M   NH       NS    Married 22    Not   42  prof
29  13.75 14   W    M   NH       NS    Married 21    Not   41  sales
30   5.62 13   W    F   Hisp     NS    Married  2    Not   21  clerical
⋮   ⋮     ⋮    ⋮    ⋮   ⋮        ⋮     ⋮       ⋮     ⋮     ⋮   ⋮
505  5.15 13   W    M   NH       S     Single   1    Union 20  service
506 26.29 17   W    M   NH       S     Married 32    Not   55  manag
507  2.01 13   W    M   NH       S     Single   0    Not   19  service
508  5.00 12   W    F   NH       S     Single  26    Not   44  clerical
509  8.75 11   W    F   NH       NS    Single  36    Not   53  service
510 12.50 14   W    F   NH       NS    Married 19    Not   39  service
511  4.00 12   W    M   NH       NS    Single  12    Not   30  service
512  4.50 16   W    M   NH       NS    Married 21    Not   43  service
513  6.50 12   W    F   NH       NS    Single  11    Not   29  prof
514  5.50 12   W    M   NH       NS    Married 10    Not   28  service
515  6.88 17   W    F   NH       NS    Married 15    Not   38  manag
516  6.15 16   W    F   NH       NS    Single  16    Not   38  prof
517  7.78 12   W    M   NH       NS    Married 23    Not   41  manuf
518  1.00 12   W    M   NH       NS    Married 24    Not   42  manag
519 12.50 17   W    F   NH       NS    Married 13    Union 36  prof
520  8.85 14   NW   F   NH       NS    Married 19    Union 39  clerical
521  4.35 11   W    F   NH       NS    Married 20    Not   37  service
522 11.36 18   W    M   NH       NS    Single   5    Not   29  prof
523  8.93  8   W    M   Hisp     NS    Married 47    Union 61  service
524  3.50 11   W    F   NH       NS    Married 33    Not   50  sales
525 26.00 14   W    M   NH       NS    Married 21    Union 41  other
526  8.00 12   W    F   NH       NS    Married 19    Not   37  manuf
527 16.00 14   W    M   NH       NS    Married 20    Union 40  other
528  5.35 12   W    F   NH       NS    Married 13    Not   31  service
529 23.25 17   NW   F   NH       NS    Married 25    Union 48  prof
530  8.63 12   NW   F   NH       NS    Married 18    Not   36  clerical
531 18.50 14   W    F   NH       NS    Single  13    Not   33  manuf
532 22.20 18   W    M   NH       NS    Married  8    Not   32  prof
533 16.26 12   NW   M   NH       NS    Single  14    Union 32  service
534 19.47 12   W    M   NH       NS    Single   9    Not   27  other